version: "3"
services:
    web:
        build: web
        ports:
            - "80:80"
        volumes:
            - "./app:/var/www/html"
#        links: 
#            - mysql
#    mysql:
#        image: mysql:5.7
#        hostname: mysqlteste
#        ports:
#            - "3306:3306"
#        volumes:
#            - "./data:/var/lib/mysql"
#        environment:
#            MYSQL_DATABASE: prestashop
#            MYSQL_USER: oticas123
#            MYSQL_PASSWORD: 123
#
